const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{webcrypto:crypto}=require('node:crypto');
async function game(){const elements=new Map(),events=[],timers=[],intervals=[];let now=100;
 const element=id=>{if(!elements.has(id))elements.set(id,{hidden:false,value:'TEST-A',checked:true,dataset:{},getContext:()=>({fillRect(){},beginPath(){},arc(){},fill(){}})});return elements.get(id);};
 const ctx=vm.createContext({console,crypto,performance:{now:()=>now},Date,innerWidth:800,innerHeight:800,matchMedia:()=>({matches:false}),setTimeout:fn=>timers.push(fn),setInterval:fn=>intervals.push(fn),requestAnimationFrame:fn=>fn(),addEventListener(){},Image:class{decode(){return Promise.resolve();}},document:{hidden:false,getElementById:element,querySelectorAll:()=>[],addEventListener(){}},StudyLogger:class{add(event,session){events.push(JSON.parse(JSON.stringify({event,session})));}flush(){}download(){}},GameCore:require('../docs/core.js'),window:{}});
 vm.runInContext(fs.readFileSync('docs/config.js','utf8'),ctx);vm.runInContext(fs.readFileSync('docs/game.js','utf8'),ctx);await new Promise(resolve=>setImmediate(resolve));
 const evaluate=code=>vm.runInContext(code,ctx);
 function solve(){const path=evaluate('GameCore.path(world.grid,player,world.goal)');for(let i=1;i<path.length;i++){now+=100;const dx=path[i][0]-path[i-1][0],dy=path[i][1]-path[i-1][1];evaluate(`move('${dx===1?'right':dx===-1?'left':dy===1?'down':'up'}')`);}}
 return {ctx,events,element,evaluate,solve,advance:ms=>now+=ms,feedback:()=>timers.shift()?.(),tick:()=>intervals.forEach(fn=>fn())};
}
test('full run records 27 exposures and decisions with correct summaries',async()=>{const g=await game();g.evaluate('start()');for(let round=0;round<3;round++){g.solve();for(let trial=0;trial<9;trial++){g.advance(200);g.evaluate("choose(promptData.correct_door,'keyboard')");g.evaluate("choose(promptData.correct_door,'keyboard')");g.feedback();}}assert.equal(g.evaluate('phase'),'ended');const decisions=g.events.filter(x=>x.event.event_type==='decision');assert.equal(decisions.length,27);assert.ok(decisions.every(x=>x.event.reaction_time_ms===200));assert.equal(g.events.filter(x=>x.event.event_type==='prompt_shown').length,27);const end=g.events.at(-1);assert.equal(end.session.status,'completed');assert.equal(end.session.score,270);assert.equal(end.session.health,100);assert.equal(end.session.round,3);assert.equal(end.session.decisions,27);});
test('timeout retains the unanswered prompt without inventing a choice',async()=>{const g=await game();g.evaluate('start()');g.solve();g.advance(91000);g.tick();assert.equal(g.events.at(-1).session.status,'timeout');assert.equal(g.events.at(-1).event.prompt_id,g.evaluate('run.prompt_id'));assert.equal(g.events.filter(x=>x.event.event_type==='decision').length,0);});
test('health depletion, enemy collision and restart have distinct session records',async()=>{const g=await game();g.evaluate('cfg.wrongPenalty=100;start()');g.solve();g.advance(120);g.evaluate("choose(promptData.correct_door==='left'?'right':'left','pointer')");assert.equal(g.events.at(-1).session.status,'health_depleted');assert.equal(g.events.at(-1).session.health,0);const oldId=g.events.at(-1).session.session_id;g.evaluate('start()');assert.notEqual(g.evaluate('run.session_id'),oldId);const step=g.evaluate('GameCore.path(world.grid,player,world.goal)[1]');g.advance(100);g.evaluate(`move('${step[0]===1?'right':'down'}')`);g.advance(700);g.tick();assert.equal(g.events.at(-1).session.status,'caught');});
