const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),{webcrypto:crypto}=require('node:crypto');
function collector(){
 const sheets={};let failReceipt=false;
 class Sheet{constructor(){this.rows=[];}getLastRow(){return this.rows.length;}appendRow(row){if(failReceipt&&this===sheets.Receipts){failReceipt=false;throw Error('simulated write failure');}this.rows.push(row);}setFrozenRows(){}getRange(r,c,n=1,m=1){const self=this;return {setFontWeight(){},getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>self.rows[r+i-1]?.[c+j-1]??'')),getValue:()=>self.rows[r-1]?.[c-1],setValues:rows=>rows.forEach((row,i)=>{self.rows[r+i-1]??=[];row.forEach((v,j)=>self.rows[r+i-1][c+j-1]=v);}),createTextFinder:id=>({matchEntireCell(){return this;},useRegularExpression(){return this;},findNext(){const i=self.rows.findIndex((row,i)=>i>=r-1&&i<r+n-1&&row[c-1]===id);return i<0?null:{getRow:()=>i+1};}})};}}
 const book={getId:()=> 'book',getSheetByName:n=>sheets[n],insertSheet:n=>sheets[n]=new Sheet()},props={};let locked=false;
 const ctx=vm.createContext({console:{error(){}},PropertiesService:{getScriptProperties:()=>({setProperty:(k,v)=>props[k]=v,getProperty:k=>props[k]})},SpreadsheetApp:{getActiveSpreadsheet:()=>book,openById:()=>book,flush(){}},LockService:{getScriptLock:()=>({waitLock(){locked=true;},hasLock:()=>locked,releaseLock(){locked=false;}})},ContentService:{MimeType:{JSON:'json',JAVASCRIPT:'js'},createTextOutput:text=>({text,setMimeType(){return this;}})}});
 vm.runInContext(fs.readFileSync('google-sheets/Code.gs','utf8'),ctx);ctx.setup();return {ctx,sheets,fail:()=>failReceipt=true};
}
function batch(sequence=1,sessionId=crypto.randomUUID()){return {batch_id:crypto.randomUUID(),events:[{event_id:crypto.randomUUID(),session_id:sessionId,sequence,event_type:'session_start',prompt_text:'=DANGEROUS()'}],session:{session_id:sessionId,sequence,decisions:0,status:'in_progress'}};}
test('collector deduplicates retries and confirms only completed writes',()=>{const {ctx,sheets,fail}=collector(),b=batch();fail();assert.equal(JSON.parse(ctx.doPost({postData:{contents:JSON.stringify(b)}}).text).ok,false);assert.equal(sheets.Events.rows.length,2);assert.equal(sheets.Receipts.rows.length,1);ctx.doPost({postData:{contents:JSON.stringify(b)}});ctx.doPost({postData:{contents:JSON.stringify(b)}});assert.equal(sheets.Events.rows.length,2);assert.equal(sheets.Sessions.rows.length,2);assert.equal(sheets.Receipts.rows.length,2);assert.equal(sheets.Events.rows[1][13],"'=DANGEROUS()");const ack=ctx.doGet({parameter:{batch_id:b.batch_id,callback:'receipt_'+'a'.repeat(32)}}).text;assert.match(ack,/"saved":true/);assert.doesNotMatch(ack,/DANGEROUS|participant/);});
test('older arrivals cannot overwrite a newer session',()=>{const {ctx,sheets}=collector(),id=crypto.randomUUID();for(const seq of [5,2])ctx.doPost({postData:{contents:JSON.stringify(batch(seq,id))}});assert.equal(sheets.Sessions.rows[1][8],5);assert.equal(sheets.Events.rows.length,3);assert.equal(JSON.parse(ctx.doPost({postData:{contents:'{}'}}).text).ok,false);});
test('logger preserves a failed batch identity when more events arrive',async()=>{const store=new Map(),sent=[];const context=vm.createContext({crypto,window:{},localStorage:{getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)},addEventListener(){},setInterval(){},AbortSignal,fetch:async(url,options)=>sent.push(JSON.parse(options.body))});vm.runInContext(fs.readFileSync('docs/logger.js','utf8')+';globalThis.Logger=StudyLogger;',context);const logger=new context.Logger('https://example.invalid',()=>{}),id=crypto.randomUUID();logger.receipt=async()=>false;logger.add({event_id:'one'},{session_id:id});await logger.flush();logger.add({event_id:'two'},{session_id:id});logger.receipt=async()=>true;await logger.flush();assert.deepEqual(sent[0],sent[1]);assert.equal(logger.queue.length,1);assert.equal(logger.queue[0].events[0].event_id,'two');await logger.flush();assert.equal(logger.queue.length,0);const restored=new context.Logger('',()=>{});assert.equal(restored.archive.length,2);});
